config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :posts do
    get 'category/:category_id', to: 'posts#index', as: :category_posts, on: :collection

      member do
        post :upvote
        post :downvote
        delete :unvote
      end
    
    resources :answers, only: [:create, :update, :destroy] do
      member do
        post :upvote
        post :downvote
        delete :unvote
      end
    end
  end



  resources :users, only: [:show]
  resources :tags, except: %i[:edit, :update]
  resources :categories, only: [:show] do
    member do
      get :tags
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="navbar-inner">
      <%= link_to posts_path, class: "d-flex align-items-center" do %>
        <span class="navbar-brand-name">G</span>
        <i class="fa-solid fa-infinity" style="font-size: 30px;"></i>
      <% end %>

      <div class="search-container">
        <%= simple_form_for :search, url: posts_path, method: :get do |f| %>
          <div class="search-form-control form-group">
            <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Search for..." />
            <button name="button" type="submit" class="btn btn-ghost">
              <i class="fas fa-search"></i>
            </button>
          </div>
        <% end %>
      </div>

      <div class="navbar-icons">
        <div class="dropdown">
          <button class="btn btn-ghost" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-th-list" style="font-size: 24px;"></i>
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            <% @categories.each do |category| %>
              <li>
                <%= link_to category_path(category), class: "dropdown-item" do %>
                  <%= category.name %>  
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>

        <%= link_to new_post_path, class: "btn btn-ghost" do %>
          <i class="fa-solid fa-plus" style="font-size: 24px;"></i>
        <% end %>

        <div class="dropdown">
          <button class="btn btn-ghost" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user-circle" style="font-size: 24px;"></i>
          </button>
          <ul class="dropdown-menu dropdown-menu-end custom-dropdown">
            <% if user_signed_in? %>
              <%= link_to "Your profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
              <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
            <% end %>
            <li>
              <button id="theme-toggle-button" class="dropdown-item" data-controller="toggle-theme" data-action="click->toggle-theme#toggleDarkMode">
                <i id="theme-icon" class="fas fa-sun" style="font-size: 18px;" data-toggle-theme-target="icon"></i>
                <span data-toggle-theme-target="modeText"></span>
              </button>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>