config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :posts do
    get 'category/:category_id', to: 'posts#index', as: :category_posts, on: :collection

      member do
        post :upvote
        post :downvote
        delete :unvote
      end
    
    resources :answers, only: [:create, :update, :destroy] do
      member do
        post :upvote
        post :downvote
        delete :unvote
      end
    end
  end



  resources :users, only: [:show]
  resources :tags, except: %i[:edit, :update]
  resources :categories, only: [:show] do
    member do
      get :tags
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :category
  has_many :answers
  has_many_attached :photos
  has_many :votes, as: :votable, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
end

def upvote
  @post = find_post
  @post.liked_by(current_user)
  flash[:notice] = "Thanks for voting #{current_user.name}"
  redirect_to @post
end

def downvote
  @post.unliked_by(current_user)
  redirect_to @post
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]
  before_action :find_post, only: %i[show upvote downvote]

  def index
    if params[:search] && params[:search][:query].present?
      @category = Category.find_by('lower(name) = ?', params[:search][:query].downcase)
      @posts = @category ? @category.posts.order(created_at: :desc) : Post.none
    elsif params[:category_id]
      @posts = Post.where(category_id: params[:category_id]).order(created_at: :desc)
    else
      @posts = Post.joins(:category)
                   .where(categories: { id: current_user.categories_of_interest })
                   .distinct
                   .order(created_at: :desc).limit(7)
    end
  end

  def show
    begin
      @post = Post.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Post not found"
      redirect_to posts_path
    end
    @answers = @post.answers.order(created_at: :desc)  # Order by newest first
    @new_answer = Answer.new
    @tags = @post.tags
  end

  def new
    @post = Post.new
    @tags = @post.category ? @post.category.tags : []
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save!
      if params[:post][:media].present?
        params[:post][:media].each do |media|
          @post.photos.attach(media)
        end
      end
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if params[:post][:media].present?
      params[:post][:media].each do |media|
        @post.photos.attach(media)
      end
    end

    if params[:remove_media].present?
      params[:remove_media].each do |photo_id|
        @post.photos.find(photo_id).purge
      end
    end

    if @post.update(post_params.except(:photos))
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path
    else
      redirect_to posts_path, alert: "Failed to delete the post 🛑."
    end
  end

  def upvote
    if current_user.voted_up_on?(@post)
      @post.unliked_by(current_user) # Unlike if already upvoted
    else
      @post.liked_by(current_user) # Like otherwise
    end
    render json: vote_counts
  end

  def downvote
    if current_user.voted_down_on?(@post)
      @post.undisliked_by(current_user) # Remove dislike if already downvoted
    else
      @post.disliked_by(current_user) # Downvote otherwise
    end
    render json: vote_counts
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id, photos: [], tag_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
    @tags = @post.category ? @post.category.tags : []
  end

  def authorize_user!
    unless @post.user == current_user
      redirect_to posts_path, alert: "You are not authorized to perform this action."
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def vote_counts
    {
      upvotes: @post.get_upvotes.size,
      downvotes: @post.get_downvotes.size
    }
  end
end

app/views/posts/_form.html.erb
<div class="form-main-styles-container">
  <div class="form-container-grid" data-controller="tags">
    <div class="header">
      <h2 class="mode-header"><%= mode %></h2>
    </div>

    <%= simple_form_for(@post, html: { multipart: true }) do |form| %>
      <div class="form-group">
        <h4><%= form.label :title, "Title" %></h4>
        <%= form.text_field :title, class: "form-control", placeholder: "Enter the post title" %>
      </div>

      <div class="form-group">
        <h4><%= form.label :content, "Content" %></h4>
        <%= form.text_area :content, class: "form-control", rows: 3, placeholder: "Share your knowledge/questions" %>
      </div>

      <div class="form-group">
        <h4><%= form.label :category_id, "Category" %></h4>
        <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a Category" },
          class: "form-control",
          data: { action: "tags#categoryChanged", tags_target: "categorySelect" } %>
      </div>

      <%  tags = @post.tags.to_json(only: [:id, :name])%>
      <div class="form-group" id="tag-values" data-tags-target="tagsContainer" data-checks="<%= tags %>">
        <%= render "tags/form", tags: @tags, post: @post, form: form %>
      </div>

      <% if @post.photos.attached? %>
        <div class="existing-media">
          <h4>Existing Photos and Videos:</h4>
          <% @post.photos.each do |media| %>
            <div class="media-item">
              <% if media.content_type.start_with?('image') %>
                <%= cl_image_tag media.key, class: 'post-image-form' %>
              <% elsif media.content_type.start_with?('video') %>
                <video controls class="post-video-form">
                  <source src="<%= media.url %>" type="<%= media.content_type %>">
                  Your browser does not support the video tag.
                </video>
              <% end %>
              <%= check_box_tag "remove_media[]", media.id %>
              <%= label_tag "remove_media_#{media.id}", "Remove this photo or video" %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :media, "Upload Photos or Videos (optional)" %>
        <%= form.input :media, as: :file, input_html: { multiple: true, accept: "image/*,video/mp4" } %>
        <small class="form-text text-muted">You can upload up to 4 photos or videos for your post.</small>
      </div>

      <div id="preview-container" class="photo-preview"></div>

      <div class="form-group-button">
        <%= form.submit (@post.persisted? ? "Update post" : "Create post"), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>


<script>
document.addEventListener('turbo:load', function() {
  const photoInput = document.getElementById('post_photos');
  const previewContainer = document.getElementById('preview-container');

  photoInput.addEventListener('change', function(event) {
    const files = Array.from(event.target.files);

    previewContainer.innerHTML = '';

    const maxFiles = 4;
    const selectedFiles = files.slice(0, maxFiles);

    selectedFiles.forEach(file => {
      const reader = new FileReader();
      reader.onload = function(e) {
        let mediaElement;
        if (file.type.startsWith("video")) {
          mediaElement = document.createElement('video');
          mediaElement.src = e.target.result;
          mediaElement.controls = true;
        } else if (file.type.startsWith("image")) {
          mediaElement = document.createElement('img');
          mediaElement.src = e.target.result;
        }
        mediaElement.className = 'post-media-preview';
        previewContainer.appendChild(mediaElement);
      };
      reader.readAsDataURL(file);
    });
  });
});
</script>

app/views/posts/_post_card.html.erb
<div class="post-card">
  <% unless local_assigns[:no_post_header] %>
    <div class="post-header">
      <div class="user-profile-photo">
        <%= image_tag(post.user.profile_photo, alt: "#{post.user.username}'s profile photo") if post.user.profile_photo.attached? %>
      </div>
      <p class="username"><strong><%= link_to_user(post.user) %></strong></p>
    </div>
  <% end %>

  <div class="post-content">
    <p><strong>Category:</strong> <span><%= link_to post.category.name, category_path(post.category) %></span></p>
    <hr class="post-divider">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p><%= post.created_at.strftime("%B %d, %Y") %></p>
    <p><%= truncate(post.content, length: 250, separator: ' ') %></p>

    <% if post.photos.attached? && post.photos.count > 1 %>
      <div id="carousel-<%= post.id %>" class="carousel slide post-carousel">
        <div class="carousel-inner">
          <% post.photos.each_with_index do |media, index| %>
            <div class="carousel-item <%= 'active' if index.zero? %>">
              <% if media.content_type.start_with?('image') %>
                <%= cl_image_tag media.key, crop: :fill, class: 'd-block w-100 post-image' %>
              <% elsif media.content_type.start_with?('video') && media.url.present? %>
                <video controls class="d-block w-100 post-video">
                  <source src="<%= media.url %>" type="<%= media.content_type %>">
                  Your browser does not support the video tag.
                </video>
              <% else %>
                <p>Unsupported media type</p>
              <% end %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= post.id %>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= post.id %>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    <% elsif post.photos.attached? %>
      <% if post.photos.first.content_type.start_with?('image') %>
        <%= cl_image_tag post.photos.first.key, crop: :fill, class: 'post-image' %>
      <% elsif post.photos.first.content_type.start_with?('video') && post.photos.first.url.present? %>
        <video controls class="post-video">
          <source src="<%= post.photos.first.url %>" type="<%= post.photos.first.content_type %>">
          Your browser does not support the video tag.
        </video>
      <% else %>
        <p>Unsupported media type</p>
      <% end %>
    <% end %>
  </div>

  <hr class="post-divider">
  <div class="post-icons" data-controller="vote">
    <span class="post-icon">
      <%= link_to "#{post_path(post)}#answers" do %>
        <i class="fa fa-comment"></i> <!-- Comment icon -->
        <span><%= post.answers.count %></span>
      <% end %>
    </span>
    <span class="post-icon">
      <%= link_to upvote_post_path(post),
        method: :post,
        remote: true,
        data: { action: "vote#upvote", vote_target: "upvoteButton", id: post.id },
        class: ("active" if post.votes.exists?(voter_id: current_user.id, votable_type: "Post", vote_flag: true)) do %>
        <i class="fa fa-thumbs-up"></i>
      <% end %>
      <span id="upvote-count-<%= post.id %>" class="ms-2" data-vote-target="upvoteCount"><%= post.get_upvotes.size %></span>
    </span>
    <span class="post-icon">
      <%= link_to downvote_post_path(post),
        method: :post,
        remote: true,
        data: { action: "vote#downvote", vote_target: "downvoteButton", id: post.id },
        class: ("active" if post.votes.exists?(voter_id: current_user.id, votable_type: "Post", vote_flag: false)) do %>
        <i class="fa fa-thumbs-down"></i>
      <% end %>
      <span id="downvote-count-<%= post.id %>" class="ms-2" data-vote-target="downvoteCount"><%= post.get_downvotes.size %></span>
    </span>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post, mode: 'Editing'%>

app/views/posts/index.html.erb
<% if @posts.empty? %>
  <p>No posts found for the specified category.</p>
<% else %>
  <div id="feed">
    <% @posts.each do |post| %>
      <%= render partial: 'posts/post_card', locals: { post: post } %>
    <% end %>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post, mode: 'Posting'%>

app/views/posts/show.html.erb
<!-- app/views/posts/show.html.erb -->
<body class="post-show">
  <% if @post.user == current_user %>
    <div class="answer-ed-actions">
      <%= link_to 'Edit post', edit_post_path(@post), class: "btn-primary" %>
      <%= button_to 'Delete post', post_path(@post), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: "btn-primary" %>
    </div>
    <hr class="post-divider">
  <% end %>

  <div class="post-header">
    <div class="user-profile-photo-show">
      <%= image_tag(@post.user.profile_photo, alt: "#{@post.user.username}'s profile photo") if @post.user.profile_photo.attached? %>
    </div>
    <p class="username"><strong><%= link_to_user(@post.user) %></strong></p>
  </div>

  <div class="post-category">
    <h2><%= link_to @post.category.name, category_path(@post.category) %></h2>
  </div>

  <div class="post-tags">
    <% if @tags.any? %>
      <ul>
        <% @tags.each do |tag| %>
          <li><%= tag.name %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No tags available for this category.</p>
    <% end %>
  </div>

  <div class="post-header-show">
    <h1><%= @post.title %></h1>
  </div>

  <div class="post-content">
    <p><%= @post.content %></p>
  </div>

  <% if @post.photos.attached? && @post.photos.count > 1 %>
    <div id="carousel-<%= @post.id %>" class="carousel slide post-carousel">
      <div class="carousel-inner">
        <% @post.photos.each_with_index do |media, index| %>
          <div class="carousel-item <%= 'active' if index.zero? %>">
            <% if media.content_type.start_with?('image') %>
              <%= cl_image_tag media.key, crop: :fill, class: 'd-block w-100 post-image' %>
            <% elsif media.content_type.start_with?('video') && media.url.present? %>
              <video controls class="d-block w-100 post-video">
                <source src="<%= media.url %>" type="<%= media.content_type %>">
                Your browser does not support the video tag.
              </video>
            <% else %>
              <p>Unsupported media type</p>
            <% end %>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= @post.id %>" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= @post.id %>" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  <% elsif @post.photos.attached? %>
    <% if @post.photos.first.content_type.start_with?('image') %>
      <%= cl_image_tag @post.photos.first.key, crop: :fill, class: 'post-image' %>
    <% elsif @post.photos.first.content_type.start_with?('video') && @post.photos.first.url.present? %>
      <video controls class="post-video">
        <source src="<%= @post.photos.first.url %>" type="<%= @post.photos.first.content_type %>">
        Your browser does not support the video tag.
      </video>
    <% else %>
      <p>Unsupported media type</p>
    <% end %>
  <% end %>

  <div class="post-icons" data-controller="vote">
    <span class="post-icon">
      <%= link_to upvote_post_path(@post),
        method: :post,
        remote: true,
        data: { action: "vote#upvote", vote_target: "upvoteButton", id: @post.id },
        class: ("active" if @post.votes.exists?(voter_id: current_user.id, votable_type: "Post", vote_flag: true)) do %>
        <i class="fa fa-thumbs-up"></i>
      <% end %>
      <span id="upvote-count-<%= @post.id %>" class="ms-2" data-vote-target="upvoteCount"><%= @post.get_upvotes.size %></span>
    </span>
    <span class="post-icon">
      <%= link_to downvote_post_path(@post),
        method: :post,
        remote: true,
        data: { action: "vote#downvote", vote_target: "downvoteButton", id: @post.id },
        class: ("active" if @post.votes.exists?(voter_id: current_user.id, votable_type: "Post", vote_flag: false)) do %>
        <i class="fa fa-thumbs-down"></i>
      <% end %>
      <span id="downvote-count-<%= @post.id %>" class="ms-2" data-vote-target="downvoteCount"><%= @post.get_downvotes.size %></span>
    </span>
  </div>

  <div class="answers-section" data-controller="comment">
    <%= form_with(model: [@post, @new_answer], local: false, html: { data: { controller: "comment-form", action: "submit->comment-form#submitComment" } }) do |form| %>
      <div class="form-group">
        <%= form.label :content, "Add a comment" %>
        <%= form.text_area :content, rows: 1, class: "form-control", data: { action: "focus->comment-form#showButtons", comment_form_target: "textarea" } %>
      </div>

      <div class="form-buttons" data-comment-form-target="buttons" style="display: none;">
        <%= form.submit "Comment", class: "btn-primary" %>
        <button type="button" class="btn-primary" data-action="click->comment-form#clearForm">Clear</button>
      </div>
    <% end %>

    <div id="answers">
      <% @answers.each do |answer| %>
        <div class="answer" id="answer-<%= answer.id %>">
          <div class="post-header-comments">
            <div class="user-profile-photo-show">
              <%= image_tag(answer.user.profile_photo, alt: "#{answer.user.username}'s profile photo") if answer.user.profile_photo.attached? %>
            </div>
            <p class="username"><strong><%= link_to_user(answer.user) %></strong></p>
          </div>
          <div class="answer-content">
            <p><%= answer.content %></p>
          </div>

          <% if answer.user == current_user %>
            <div class="answer-actions">
              <button class="btn-primary" data-action="click->comment#edit">Edit</button>
              <%= button_to post_answer_path(@post, answer), method: :delete, class: "btn-primary", data: { action: "click->comment#deleteComment", comment_id: answer.id, url: post_answer_path(@post, answer) } do %>
                Delete
              <% end %>
            </div>

            <div class="edit-answer-form" style="display: none;">
              <%= form_with(model: [@post, answer], local: true, html: { data: { action: "submit->comment#update" } }) do |form| %>
                <div class="form-group">
                  <%= form.label :content, "Edit your comment" %>
                  <%= form.text_area :content, rows: 1, class: "form-control", value: answer.content %>
                </div>
                <div class="form-buttons">
                  <%= form.submit "Update", class: "btn-primary" %>
                  <button type="button" class="btn-primary" data-action="click->comment#cancelEdit">Cancel</button>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</body>