config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :posts do
    get 'category/:category_id', to: 'posts#index', as: :category_posts, on: :collection

      member do
        post :upvote
        post :downvote
        delete :unvote
      end
    
    resources :answers, only: [:create, :update, :destroy] do
      member do
        post :upvote
        post :downvote
        delete :unvote
      end
    end
  end



  resources :users, only: [:show]
  resources :tags, except: %i[:edit, :update]
  resources :categories, only: [:show] do
    member do
      get :tags
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
  has_many :user_categories, dependent: :destroy
  has_many :interested_users, through: :user_categories, source: :user
  has_many :tags, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :set_categories, only: [:index, :show]

  def tags
    @category = Category.find(params[:id])
    @tags = @category.tags

    respond_to do |format|
      format.json { render json: @tags.select(:id, :name) }
    end
  end

  def index
    @categories
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def new
  end

  def create
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end
end

app/views/categories/show.html.erb
<h1 class="category-title"><%= @category.name %></h1>

<% @category.posts.each do |post| %>
<%= render partial: 'posts/post_card', locals: { post: post } %>
<% end %>

app/views/categories/tags.js.erb
<% if @tags.any? %>
  <h4>Select Tags:</h4>
  <% @tags.each do |tag| %>
    <div>
      <input type="checkbox" name="post[tag_ids][]" value="<%= tag.id %>" <%= @post.tags.include?(tag) ? "checked" : "" %>>
      <label for="post_tag_ids_<%= tag.id %>"><%= tag.name %></label>
    </div>
  <% end %>
<% else %>
  <p>No tags available for this category.</p>
<% end %>